openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: OK
  /:id:
    get:
      summary: Get User By ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User found by ID
        '400':
          description: Bad Request
    put:
      summary: Update User By ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
      responses:
        '200':
          description: Updated User
        '400':
          description: Bad Request
    delete:
      summary: Delete User By ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User Deleted
        '400':
          description: Bad Request
  /exists/:email:
    get:
      summary: Check if User Exists
      parameters:
      - name: email
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Users Exists
        '400':
          description: Bad Request
  /authenticate:
    post:
      summary: Authenticate User
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
      responses:
        '200':
          description: OK
  /:
    post:
      summary: Add User
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
      responses:
        '200':
          description: OK
  /{id}:
    get:
      summary: Get User By ID
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
      responses:
        '200':
          description: OK
    put:
      summary: Update User
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
      responses:
        '200':
          description: OK
    delete:
      summary: Delete User
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
      responses:
        '200':
          description: OK
  /exists/{email}:
    get:
      summary: Check if User Exists
      parameters:
      - in: path
        name: email
        schema:
          type: string
          format: email
        required: true
      responses:
        '200':
          description: OK
components:
  schemas: {}
